//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Repositorio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMCAP;CATINIC;CATFIM;DESCRICAO;DESCRABREV;
        ///1;A00;B99;Capítulo I - Algumas doenças infecciosas e parasitárias;I.  Algumas doenças infecciosas e parasitárias;
        ///2;C00;D48;Capítulo II - Neoplasias [tumores];II.  Neoplasias (tumores);
        ///3;D50;D89;Capítulo III  - Doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários;III. Doenças sangue órgãos hemat e transt imunitár;
        ///4;E00;E90;Capítulo IV - Doenças endócrinas, nutricionais e metabólicas;IV.  Doenças endócrinas nutricionais e metabólicas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CID_10_CAPITULOS {
            get {
                return ResourceManager.GetString("CID_10_CAPITULOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAT;CLASSIF;DESCRICAO;DESCRABREV;REFER;EXCLUIDOS;
        ///A00;;Cólera;A00   Colera;;;
        ///A01;;Febres tifóide e paratifóide;A01   Febres tifoide e paratifoide;;;
        ///A02;;Outras infecções por Salmonella;A02   Outr infecc p/Salmonella;;;
        ///A03;;Shiguelose;A03   Shiguelose;;;
        ///A04;;Outras infecções intestinais bacterianas;A04   Outr infecc intestinais bacter;;;
        ///A05;;Outras intoxicações alimentares bacterianas, não classificadas em outra parte;A05   Outr intox alimentares bacter NCOP;;;
        ///A06;;Amebíase;A06   Amebiase;;;
        ///A0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CID_10_CATEGORIAS {
            get {
                return ResourceManager.GetString("CID_10_CATEGORIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATINIC;CATFIM;DESCRICAO;DESCRABREV;
        ///A00;A09;Doenças infecciosas intestinais;Doenças infecciosas intestinais;
        ///A15;A19;Tuberculose;Tuberculose;
        ///A20;A28;Algumas doenças bacterianas zoonóticas;Algumas doenças bacterianas zoonóticas;
        ///A30;A49;Outras doenças bacterianas;Outras doenças bacterianas;
        ///A50;A64;Infecções de transmissão predominantemente sexual;Infecções de transmissão predominantemente sexual;
        ///A65;A69;Outras doenças por espiroquetas;Outras doenças por espiroquetas;
        ///A70;A74;Outras doenças causada [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CID_10_GRUPOS {
            get {
                return ResourceManager.GetString("CID_10_GRUPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBCAT;CLASSIF;RESTRSEXO;CAUSAOBITO;DESCRICAO;DESCRABREV;REFER;EXCLUIDOS;
        ///A000;;;;Cólera devida a Vibrio cholerae 01, biótipo cholerae;A00.0 Colera dev Vibrio cholerae 01 biot cholerae;;;
        ///A001;;;;Cólera devida a Vibrio cholerae 01, biótipo El Tor;A00.1 Colera dev Vibrio cholerae 01 biot El Tor;;;
        ///A009;;;;Cólera não especificada;A00.9 Colera NE;;;
        ///A010;;;;Febre tifóide;A01.0 Febre tifoide;;;
        ///A011;;;;Febre paratifóide A;A01.1 Febre paratifoide A;;;
        ///A012;;;;Febre paratifóide B;A01.2 Febre paratifoide B;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CID_10_SUBCATEGORIAS {
            get {
                return ResourceManager.GetString("CID_10_SUBCATEGORIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAT;DESCRICAO;REFER;
        ///M8000/0;Neoplasia benigna;;
        ///M8000/1;Neoplasia de comportamento incerto se benigno ou maligno;;
        ///M8000/3;Neoplasia maligna;;
        ///M8000/6;Neoplasia metastática;;
        ///M8001/0;Células tumorais, benignas;;
        ///M8001/1;Células tumorais, incerto se benignas ou malignas;;
        ///M8001/3;Células tumorais malignas;;
        ///M8002/3;Tumor maligno, tipo de células pequenas;;
        ///M8003/3;Tumor maligno, tipo de células gigantes;;
        ///M8004/3;Tumor maligno, tipo de células fusiformes;;
        ///M8010/0;Tumor epitelial benigno;;
        ///M8010 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CID_O_CATEGORIAS {
            get {
                return ResourceManager.GetString("CID_O_CATEGORIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATINIC;CATFIM;DESCRICAO;REFER;
        ///M800;M800;Neoplasias SOE;;
        ///M801;M801;Neoplasias epiteliais SOE;;
        ///M805;M805;Neoplasias de células escamosas;;
        ///M809;M809;Neoplasias de células basais;;
        ///M812;M812;Papilomas e carcinomas de células de transição;;
        ///M814;M814;Adenomas e adenocarcinomas;;
        ///M839;M839;Neoplasias dos anexos e apêndices cutâneos;;
        ///M843;M843;Neoplasias mucoepidemóides;;
        ///M844;M844;Neoplasias císticas, mucinosas e serosas;;
        ///M850;M850;Neoplasias ductais, lobulares e medulares;;
        ///M855;M855;Neoplasias [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CID_O_GRUPOS {
            get {
                return ResourceManager.GetString("CID_O_GRUPOS", resourceCulture);
            }
        }
    }
}
